name: TicTacToe
main: net.nocpiun.plugin.tictactoe.TicTacToeMain
version: 1
author: NriotHrreion
commands:
  tictactoe:
    description: "Play TicTacToe game"
    usage: "/<command>"
  multitictactoe:
    description: "Play MultiTicTacToe game"
    usage: "/<command> <player_name>"
  ticconfirm:
    description: "Confirm game"
    usage: "/<command>"
